# Changes here will be overwritten by Copier
_commit: 552aecd
_src_path: https://github.com/koosie0507/cs-ubb-eduml-app.git
author_email: andrei.olar@ubbcluj.ro
author_name: Andrei Olar
experiment_name: cs-ubb-eduml-app-experiment
github_namespace: koosie0507
github_repo: cs-ubb-eduml-app
package_name: cs_ubb_eduml_app
project_name: CS UBB EduML App
project_slug: cs-ubb-eduml-app
