image:
  repository: ghcr.io/koosie0507/cs-ubb-eduml-app
  tag: main-7802ec6

# customize the name of the Mlflow experiment
#experiment: cs-ubb-eduml-app-experiment

entrypoint:
  command:
    - "python"
    - "-m"
    - "cs_ubb_eduml_app"
  parameters:
    - name: alpha
      value: 0.6
    - name: l1Ratio
      value: 0.1

# Configure storage options for the training data
storage:
  type: minio
  minio:
    uri: "minio.minio.svc.cluster.local:80"
    credentials: "minio-access"
    bucket: "test-bucket"
    path: "cs-ubb-mlops-test-1/wine-quality.csv"
