image:
  repository: ghcr.io/koosie0507/cs-ubb-eduml-app
  tag: main-f10c6cf

# customize the name of the Mlflow experiment
#experiment: cs-ubb-eduml-app-experiment

entrypoint:
  command:
    - "python"
    - "-m"
    - "cs_ubb_eduml_app"
  parameters:
    - name: alpha
      value: 0.6
    - name: l1Ratio
      value: 0.1

storage:
  type: minio

  minio:
    bucket: "test-bucket"
    path: "cs-ubb-mlops-test-1/wine-quality.csv"

resources:
  cpu: 1500m
  memory: 2Gi