image:
  repository: ghcr.io/koosie0507/cs-ubb-eduml-app  # change me
  tag: main-f488fdb  # change me

entrypoint:
  command:
    - "python"
    - "-m"
    - "cs_ubb_mlops_test"
  # parameters are kebab-cased and prefixed with double dash and passed
  # as command line arguments to the
  # e.g. l1Ratio becomes
  parameters:
    - name: alpha
      value: 0.6
    - name: l1Ratio
      value: 0.1
